### ISSUE TITLE
关于TagsView问题

### ISSUE THREAD

**Issue by taolei1990** [jzfai/vue3-admin-template#10]
![image](https://user-images.githubusercontent.com/23173640/154915011-ae3aab1d-e959-445d-9add-00ebcc27cd67.png)
优化一下 Tags 第一个固定为首页 且不能有删除图标

**Comment by jzfai** [comment]
考虑到你第一个有可能不是首页的情况，如刷新进来就是其他页面，如果你需要首页不能删除，可以在删除的地方加个判断就行
