### ISSUE TITLE
当页面高度超出浏览器可视区域后超出部分被遮住

### ISSUE THREAD

**Issue by yuancihang2** [jzfai/vue3-admin-template#12]
当页面高度超出浏览器可视区域后超出部分被遮住，并没有出现滚动条以支持向下滑动

**Comment by yuancihang2** [comment]
经过测试发现

将以下样式
.show-tag-view {
  height: calc(100vh - #{$navBarHeight} - #{$tagViewHeight}) !important;
}

改为
.show-tag-view {
  height: 100%;
  overflow: hidden;
}

页面超出可视区域才会出现滚动条

**Comment by jzfai** [comment]
默认超出自动隐藏的，可以为父元素添加  scroll-y 超出后自动滚动
