### ISSUE TITLE
packagr.json 依赖关系中未列出模块（store）and 依赖报错

### ISSUE THREAD

**Issue by ZYong9908** [jzfai/vue3-admin-template#23]
1.  packagr.json 依赖关系中未列出模块（store）

如图，但是运行正常
![image](https://user-images.githubusercontent.com/44081531/212634161-ca63a2cb-e31a-4161-acec-3860a4304b7d.png)

2. 安装依赖报错（可能？初次使用pnpm）
但是运行正常
![image](https://user-images.githubusercontent.com/44081531/212634910-9da7b82b-6b85-42b4-a7f4-aec7da1ae05b.png)

**Comment by jzfai** [comment]
报错的话先安装依赖

**Comment by ZYong9908** [comment]
> 报错的话先安装依赖

运行 pnpm i 之后的问题

**Comment by jzfai** [comment]
安装完依赖后，尝试重启下vscode

**Comment by ZYong9908** [comment]
使用webstrome，目前问题依旧，不知是否我个例，也试过删掉整个项目

kuanghua ***@***.***> 于 2023年2月1日周三 14:11写道：

**Comment by ZYong9908** [comment]
> 安装完依赖后，尝试重启下vscode

使用webstrome，目前问题依旧，不知是否我个例，也试过删掉整个项目

**Comment by ZYong9908** [comment]
没有影响使用，感觉可能是ws的bug
