### ISSUE TITLE
出现错误Cannot access 'Layout' before initialization

### ISSUE THREAD

**Issue by MissTe** [jzfai/vue3-admin-template#24]
报错：Uncaught ReferenceError: Cannot access 'Layout' before initialization
操作：
把dashboard/index.vue里的切换主题等相关代码，搬迁到 app-main/navbar中时（或某子组件中）。会出现如上报错。
然后，尝试将import { useConfigStore } from '@/store/config'等相关js代码注释掉，错误就消失了。

不知报错原因是什么？ 目前无法把切换主题等的代码搬到任何一个子组件里。

**Comment by jzfai** [comment]
无法复现问题，请提供下复现问题的最小例子

**Comment by MissTe** [comment]
你好，我已经收到了你的邮件，祝你生活愉快！

**Comment by MissTe** [comment]
> 无法复现问题，请提供下复现问题的最小例子
![微信截图_20230201152627](https://user-images.githubusercontent.com/14817793/215979237-169e45a0-2875-4490-a81d-f08a29c1e01f.png)
![微信截图_20230201152905](https://user-images.githubusercontent.com/14817793/215979258-68099f26-b8ad-47af-91a5-11132e23f61b.png)

然后就如下报错了
![微信截图_20230201153212](https://user-images.githubusercontent.com/14817793/215979360-8e6acabc-2cca-4b89-adf9-d70167ea1aee.png)

**Comment by TaHongLingBo** [comment]
<img width="1162" height="598" alt="Image" src="https://github.com/user-attachments/assets/e1a09d01-adee-4e78-bafd-0e36b984cd48" />我把底下注掉改成上面就没这个问题了,不知道有没有用

**Comment by MissTe** [comment]
你好，我已经收到了你的邮件，祝你生活愉快！
