### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by thomasinspectorio** [jzfai/vue3-admin-template#27]
Hi,
I am on tag version v2.1.0. Can you help to check why install lib failed:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue3-admin-template@2.0.5
npm ERR! Found: vite@4.5.1
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0" from @vitejs/plugin-legacy@2.3.1
npm ERR! node_modules/@vitejs/plugin-legacy
npm ERR!   dev @vitejs/plugin-legacy@"^2.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by jzfai** [comment]
update the code to test
