### ISSUE TITLE
安装依赖后，无法启动成功

### ISSUE THREAD

**Issue by dtboy1995** [jzfai/vue3-admin-template#30]
首先感谢作者大大，大爱js版本
按照文档的流程，到pnpm run dev的时候发生以下错误
![image](https://github.com/jzfai/vue3-admin-template/assets/19227547/a7719cc8-cc8b-4f8c-b5b7-db1dfb07421f)
环境为
windows10
![image](https://github.com/jzfai/vue3-admin-template/assets/19227547/2d5de4fa-c14a-443e-8028-c0f07d8939e0)

**Comment by jzfai** [comment]
已fix
