### ISSUE TITLE
关于动态路由疑问

### ISSUE THREAD

**Issue by Huangpuguang** [jzfai/vue3-admin-template#4]
请问一下，在beforeEach中addRoute之前，不用把之前添加的动态路由清空吗。

**Comment by Huangpuguang** [comment]
其实我主要不理解的还是如果不清空的话，会不会出现第一次admin登录，然后切换成editor登录，路由表没清空，那么是不是editor能通过在浏览器输入URL的方式访问到原本只有admin才能访问的路由，尽管这个路由在editor的左侧菜单栏没有显示。不过我后面试了（editor访问page permission页面），是不行的，会出现404，我想请问这是怎么做到的。

**Comment by jzfai** [comment]
vue-route4中没有提供清空路由的方法
我使用了location.reload()；来清空路由

**Comment by Huangpuguang** [comment]
好的！多谢大佬解答！没想到还有这种操作！
