### ISSUE TITLE
您好，能不能麻烦作者自我评价一下这个项目能否在生产环境使用？

### ISSUE THREAD

**Issue by Pidbid** [jzfai/vue3-admin-template#7]
目前是2021年12月18日，由于vue-admin-template/admin 项目为vue2.0项目，想转3.0，请问这个项目目前是否可以投入生产环境？还请作者自评一下

**Comment by jzfai** [comment]
1.如果是新开发的项目，建议使用vue3这个架构，vue3比vue2的性能好太多，现在用vue2开发，后期你也是要迁移
2.使用此架构之前，请先架构看一遍，把一些核心的部分看懂以便更好的解决问题
3.这个架构，已经有不少人用来开发项目了，已经上了生产的，作者自己也在用
4.评估你的项目难度，用此架构把你项目中的一些难点先实现下，看下是否存在问题

**Comment by jzfai** [comment]
如果有问题，及时反馈

**Comment by Pidbid** [comment]
好的  谢谢
